### ISSUE TITLE
Potential Java Issue

### ISSUE THREAD

**Issue by Russia2013** [shadowmage45/AncientWarfare#36]
I have tried to install this mod on forge and It seems to be having a problem. I felt it would be a great idea to bringthis up so it could be resolved. My minecraft version is 1.6.4 and forge version is 9.11
Here is the crash report.
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/14/13 9:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: shadowmage.ancient_warfare.common.AWCore
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:521)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: shadowmage.ancient_warfare.common.AWCore
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:61)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:462)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
    ... 38 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 23678496 bytes (22 MB) / 132800512 bytes (126 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 5 mods loaded, 5 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed
    Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed
    ClaySoldiersMod{2.0.0} [Clay Soldiers Mod](CSM_v200a.jar) Unloaded->Constructed
    AncientWarfare{1.1.037-beta-MC164} [Ancient Warfare](shadowmage) Unloaded->Errored

**Comment by TechStack** [comment]
have you tried it without ClaySoldiersMod to see if it is a conflict ?

**Comment by Russia2013** [comment]
I tried that and it still crashes. The latest version of forge is 9.11.1.953 correct

On Saturday, December 14, 2013 10:27 PM, TechStack notifications@github.com wrote:

have you tried it without ClaySoldiersMod to see if it is a conflict ?

**Comment by shadowmage45** [comment]
generally a class-not-found error is an install/setup/configuration error, even more-so when the 'not found' class is pointing directly to the main mod-file. (this means that FML found the file the first time to begin loading, but something in the JVM/setup is screwed up and it cannot find the file after the initial parsing and discovery)

I have no idea on forge 953 -- have been unable to get a dev setup working since they switch to the gradle system.  There could be some issues there.

I would recommend trying forge 935, as that is what I am using to build and compile from.

also, this line is a bit scary:
JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe

are you using a non-standard JVM or java setup?

**Comment by Russia2013** [comment]
If it possibly is an install error than maybe I should start with how I install the mod.
After I download the Mod I than copy and paste it into the mod folder in minecraft. I understand I am not suppose to extract it. As I am not familiar with working with  java I do not mess with the Mod or try to change things.I noticed I have the same issue with other mods I have tried to Install. Usually when a mod does not work i will redownload itand reinstall it.

On Sunday, December 15, 2013 4:36 PM, shadowmage45 notifications@github.com wrote:

generally a class-not-found error is an install/setup/configuration error, even more-so when the 'not found' class is pointing directly to the main mod-file.
I have no idea on forge 953 -- have been unable to get a dev setup working since they switch to the gradle system.  There could be some issues there.
I would recommend trying forge 935, as that is what I am using to build and compile from.
also, this line is a bit scary:
JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe
are you using a non-standard JVM or java setup?

**Comment by shadowmage45** [comment]
The MCP version for forge/fml-953 should be MCP 8.11, not MCP 8.09. (8.09 is correct for the 935 release though I believe)(this could be just a spelling/version error in fml code however, wouldn't be the first time).  It appears that you have remnants of multiple forge installations in your minecraft setup / jars.  

I would recommend doing a clean install of minecraft (backup your worlds, etc, and delete your .minecraft folder, relaunch the launcher to redownload it all for you), and then a clean install of forge on top of that (d/l the forge installer, and install it into the fresh MC setup).

If this does not solve the issue, I'm at a bit of a loss.

**Comment by Russia2013** [comment]
I uninstalled minecraft and forge and reinstalled them both.
After reinstalling the mod and then starting the game it crashed again.
My understanding of how to install the mod is after I download the mod I then  copy and paste it into the mod folder than run the game.
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/16/13 4:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: shadowmage.ancient_warfare.common.AWCore
at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:521)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
at net.minecraft.client.main.Main.main(SourceFile:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: shadowmage.ancient_warfare.common.AWCore
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:61)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:462)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
... 10 more
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
... 38 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.6.4
Operating System: Windows 7 (x86) version 6.1
Java Version: 1.7.0_45, Oracle Corporation
Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
Memory: 29466312 bytes (28 MB) / 125374464 bytes (119 MB) up to 518979584 bytes (494 MB)
JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Suspicious classes: FML and Forge are installed
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 4 mods loaded, 4 mods active
mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed
Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed
AncientWarfare{1.1.037-beta-MC164} [Ancient Warfare](shadowmage) Unloaded->Errored

On Monday, December 16, 2013 1:05 PM, shadowmage45 notifications@github.com wrote:

The MCP version for forge/fml-953 should be MCP 8.11, not MCP 8.09. (8.09 is correct for the 935 release though I believe)(this could be just a spelling/version error in fml code however, wouldn't be the first time).  It appears that you have remnants of multiple forge installations in your minecraft setup / jars. 
I would recommend doing a clean install of minecraft (backup your worlds, etc, and delete your .minecraft folder, relaunch the launcher to redownload it all for you), and then a clean install of forge on top of that (d/l the forge installer, and install it into the fresh MC setup).
If this does not solve the issue, I'm at a bit of a loss.

**Comment by Russia2013** [comment]
I understand this means that the loader cannot find the class so it cant load. Is there a way I can direct the computer to find the class. I had a similar issue with other mods. I am quite skilled with computers in the hardware area. I have never really played around with computer programing despite I was tempted to try to create my own operating systems so I do not have to buy windows any more.

On Monday, December 16, 2013 4:35 PM, Michael Stewart duranduran197852@yahoo.com wrote:

I uninstalled minecraft and forge and reinstalled them both.
After reinstalling the mod and then starting the game it crashed again.
My understanding of how to install the mod is after I download the mod I then  copy and paste it into the mod folder than run the game.
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/16/13 4:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: shadowmage.ancient_warfare.common.AWCore
at cpw.mods.fml.common.LoadController.transition(LoadController.java:156)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:521)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:183)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
at net.minecraft.client.main.Main.main(SourceFile:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: shadowmage.ancient_warfare.common.AWCore
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:61)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:462)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
... 10 more
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
... 38 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.6.4
Operating System: Windows 7 (x86) version 6.1
Java Version: 1.7.0_45, Oracle Corporation
Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
Memory: 29466312 bytes (28 MB) / 125374464 bytes (119 MB) up to 518979584 bytes (494 MB)
JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Suspicious classes: FML and Forge are installed
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 4 mods loaded, 4 mods active
mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed
Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed
AncientWarfare{1.1.037-beta-MC164} [Ancient Warfare](shadowmage) Unloaded->Errored

On Monday, December 16, 2013 1:05 PM, shadowmage45 notifications@github.com wrote:

The MCP version for forge/fml-953 should be MCP 8.11, not MCP 8.09. (8.09 is correct for the 935 release though I believe)(this could be just a spelling/version error in fml code however, wouldn't be the first time).  It appears that you have remnants of multiple forge installations in your minecraft setup / jars. 
I would recommend doing a clean install of minecraft (backup your worlds, etc, and delete your .minecraft folder, relaunch the launcher to redownload it all for you), and then a clean install of forge on top of that (d/l the forge installer, and install it into the fresh MC setup).
If this does not solve the issue, I'm at a bit of a loss.

**Comment by shadowmage45** [comment]
I'm running a forge-953 w/ancient warfare setup at home without issue, so I know that the mod works/installs loads fine.  There has to be something improperly configured on your computer to be causing the issue, as the process you describe for the install sounds normal.  I have no idea what the problem could be...classloaders and such are not my area of understanding, and the only time I've seen these class-loader related issues have been user setup/install issues.

Are you leaving the mod in the .zip file? You need to place the entire .zip file into the /mods folder.

Do you have any strange characters in the filepath for your username on windows?  I know there have been reports of issues regarding this w/ forge/FML in general.

I'm just throwing out random ideas...things that I have seen cause errors before....

**Comment by TechStack** [comment]
@Russia2013  i'm running Forge version 9.11.1.953 and AW version 1.1.037-Beta-MC164 and I do not have this issue.
You may want to check the spelling of the mods folder if you maually created it. It should be lower case "mods" 
I've heard some people have had issues if they manually created it with an upper case M

**Comment by Russia2013** [comment]
Is the NEI Plug in necessary?

On Monday, December 16, 2013 5:09 PM, shadowmage45 notifications@github.com wrote:

I'm running a forge-953 w/ancient warfare setup at home without issue, so I know that the mod works/installs loads fine.  There has to be something improperly configured on your computer to be causing the issue, as the process you describe for the install sounds normal.  I have no idea what the problem could be...classloaders and such are not my area of understanding, and the only time I've seen these class-loader related issues have been user setup/install issues.
Are you leaving the mod in the .zip file? You need to place the entire .zip file into the /mods folder.
Do you have any strange characters in the filepath for your username on windows?  I know there have been reports of issues regarding this w/ forge/FML in general.
I'm just throwing out random ideas...things that I have seen cause errors before....

**Comment by shadowmage45** [comment]
NEI plugin is optional -- it should only be installed if you already have NEI installed AND you want AW recipes to show up in NEI.

**Comment by shadowmage45** [comment]
I could not find any problems on this end, and this appears to be an install/setup issue, and not anything actually pertaining to the mod.

Please re-open/comment if this is indeed still an issue.
