### ISSUE TITLE
NPE at at shadowmage.ancient_warfare.common.civics.TECivic.func_70302_i_(TECivic.java:720)

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#65]
I'm still gathering information here, but I have an Extra Utilities transfer node connected to a AW civic (not sure which type) an when I LOOK at it, I get an NPE on the client side and it crashes.  Server is fine.  AW .46 build, Extra Utilities 1.0.3c.  It seems to have only happened when I upgraded AW from .44 to .46

[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT] Time: 6/24/14 3:13 PM
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT] Description: Unexpected error
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT] 
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT] java.lang.NullPointerException
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at shadowmage.ancient_warfare.common.civics.TECivic.func_70302_i_(TECivic.java:720)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at extrautils.tileentity.transfernodes.TNHelper.isValidTileEntity(TNHelper.java:132)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at extrautils.tileentity.transfernodes.TNHelper.isValidTileEntity(TNHelper.java:81)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at extrautils.tileentity.transfernodes.pipes.PipeBase.shouldConnectToTile(PipeBase.java:90)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at extrautils.tileentity.transfernodes.BlockTransferPipe.getPipeModel(BlockTransferPipe.java:235)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at extrautils.tileentity.transfernodes.BlockTransferPipe.getWorldModel(BlockTransferPipe.java:196)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at extrautils.block.BlockMultiBlock.func_71902_a(BlockMultiBlock.java:83)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.renderer.RenderBlocks.func_78612_b(RenderBlocks.java:440)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.renderer.WorldRenderer.func_78907_a(WorldRenderer.java:224)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1574)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1129)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1002)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.client.main.Main.main(SourceFile:101)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at java.lang.reflect.Method.invoke(Unknown Source)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[B#439]  2014-06-24 15:13:12 [INFO] [STDOUT]    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by keenerb** [comment]
OK, I think I figured out what's up.  I have a warehouse block that has somehow managed to be corrupted.  This is what I get when I right-click on it.

16:14:38 [SEVERE] A critical server error occured handling a packet, kicking 10747
java.lang.NullPointerException
        at shadowmage.ancient_warfare.common.utils.InventoryTools.getCompactedInventory(InventoryTools.java:108)
        at shadowmage.ancient_warfare.common.container.ContainerCivicWarehouse.<init>(ContainerCivicWarehouse.java:60)
        at shadowmage.ancient_warfare.common.network.GUIHandler.getServerGuiElement(GUIHandler.java:257)
        at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:361)
        at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:352)
        at shadowmage.ancient_warfare.common.network.GUIHandler.openGUI(GUIHandler.java:729)
        at shadowmage.ancient_warfare.common.civics.TECivicWarehouse.onInteract(TECivicWarehouse.java:119)
        at shadowmage.ancient_warfare.common.civics.BlockCivic.onBlockClicked(BlockCivic.java:75)
        at shadowmage.ancient_warfare.common.block.AWBlockBase.func_71903_a(AWBlockBase.java:82)
        at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:516)
        at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:897)
        at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonPlayerConnection.func_72472_a(CommonPacketHandler.java:349)
        at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:465)
        at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:234)
        at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
        at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:37)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:906)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:773)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:655)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

**Comment by keenerb** [comment]
The warehouse civic has also lost it's boundaries.  It doesn't highlight the actual warehouse area.  Another warehouse in a seperate dimension seems to be fine.

**Comment by shadowmage45** [comment]
Sounds like something is corrupting your game data.

Please let me know if you can -duplicate- the issue, and the steps needed to do so -- that information will be necessary in order for me to begin looking into a solution.

Also, I might -not- be issuing an update/patch, as I'm pretty much done working with the 1.6 code.  If you can provide the details needed to track down and fix the issue, me actually implementing it becomes much more likely.
