### ISSUE TITLE
Unable to equip equipment onto any NPC

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#7]
0.34, MCPC+ 150

I get kicked from the server, log in and armor is lying on ground.

```
11:29:07 [SEVERE] A critical server error occured handling a packet, kicking 69357
java.lang.IndexOutOfBoundsException: Index: 47, Size: 46
at java.util.ArrayList.rangeCheck(ArrayList.java:604)
at java.util.ArrayList.get(ArrayList.java:382)
at net.minecraft.inventory.Container.func_75144_a(Container.java:233)
at net.minecraft.network.NetServerHandler.func_72523_a(NetServerHandler.java:2004)
at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonPlayerConnection.func_72523_a(CommonPacketHandler.java:277)
at net.minecraft.network.packet.Packet102WindowClick.func_73279_a(Packet102WindowClick.java:46)
at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:913)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:327)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:662)
at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
11:29:07 [WARNING] Failed to handle packet for Skuli_Steinulf/192.168.5.1: java.lang.IndexOutOfBoundsException: Index: 47, Size: 46
java.lang.IndexOutOfBoundsException: Index: 47, Size: 46
at java.util.ArrayList.rangeCheck(ArrayList.java:604)
at java.util.ArrayList.get(ArrayList.java:382)
at net.minecraft.inventory.Container.func_75144_a(Container.java:233)
at net.minecraft.network.NetServerHandler.func_72523_a(NetServerHandler.java:2004)
at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonPlayerConnection.func_72523_a(CommonPacketHandler.java:277)
at net.minecraft.network.packet.Packet102WindowClick.func_73279_a(Packet102WindowClick.java:46)
at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:913)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:327)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:780)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:662)
at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
11:29:07 [INFO] §eSkuli_Steinulf left the game.
```

**Comment by shadowmage45** [comment]
Can you try the same thing without MCPC?

I have tried all combinations of equipping armor onto NPCs and cannot duplicate the error.  Additionally, the indices that your crash report are listing are quite a bit off from what they should be for a vanilla inventory/container (e.g. should give an inventory size of 40 for a normal player+soldier inventory, whereas your crash report is saying 46 slots).

This looks to be more like some other mod messing with the slots/packets/data in ways that it should not be, but will investigate further if I can get more information to allow me to duplicate the issue.

**Comment by keenerb** [comment]
Without MCPC I get:

```
2013-12-05 19:18:29 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking 713
java.lang.IndexOutOfBoundsException: Index: 37, Size: 36
        at java.util.ArrayList.rangeCheck(ArrayList.java:604)
        at java.util.ArrayList.get(ArrayList.java:382)
        at net.minecraft.inventory.Container.func_75144_a(SourceFile:190)
        at net.minecraft.network.NetServerHandler.func_72523_a(NetServerHandler.java:926)
        at net.minecraft.network.packet.Packet102WindowClick.func_73279_a(SourceFile:31)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
        at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
        at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
        at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2013-12-05 19:18:29 [WARNING] [Minecraft-Server] Failed to handle packet for Skuli_Steinulf/192.168.5.1: java.lang.IndexOutOfBoundsException: Index: 37, Size: 36
java.lang.IndexOutOfBoundsException: Index: 37, Size: 36
        at java.util.ArrayList.rangeCheck(ArrayList.java:604)
        at java.util.ArrayList.get(ArrayList.java:382)
        at net.minecraft.inventory.Container.func_75144_a(SourceFile:190)
        at net.minecraft.network.NetServerHandler.func_72523_a(NetServerHandler.java:926)
        at net.minecraft.network.packet.Packet102WindowClick.func_73279_a(SourceFile:31)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
        at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
        at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
        at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

**Comment by keenerb** [comment]
My mod list:

```
aPerf-1.6.1.1.jar
aquaculture_1.2.4.zip
backpack-latest.zip
BACKUP
BetterDungeons2.zip
betterfurnacesV3.4.dev.zip
bspkrscorev5.0.zip
buildcraft-A-1.6.2-4.1.2.jar
butterflymania[1.6.4]_universal_v0.9.3.zip
Carpenter's Blocks v1.9.5 - MC 1.6+.zip
CaveGen
codechickencore 0.9.0.6.jar
ConfigMod for MC v1.6.4.zip
CoroAI for MC v1.6.4.zip
CustomMobSpawner 2.3.2-DEVR1.zip
customnpcs_1.6.2.zip
doggy talents - v1.5.0a.zip
DrZharks MoCreatures Mod v6.0.2-DEVR1 (1).zip
Dynmap-1.9-forge-9.10.0.jar
EnchantingPlus-1.16.5.zip
enderstorage 1.4.3.5.jar
erebus0.1.zip
ExtendedRenderer for MC v1.6.4.zip
familiars_API_1.6.4a.zip
familiars_DefaultMobPack_1.6.4a.zip
familiars_ExtendedFamPack_1.6.4a.zip
forgeperms-1.6.1.4 WithoutPEX.jar
hamsterrific[1.6.4]V2.0.zip
immibis-core-57.1.4.jar
immibis-microblocks-57.2.3.jar
ironchest-universal-1.6.4-5.4.1.645.zip
keithyutils-1.6.2-1.2b.jar
metallurgy-1.6.2-3.3.75.jar
millenaire
millenaire-custom
millenaire-jar-5.1.10
mobiuscore_1.0.1.jar
ModBuild for MC v1.6.4.zip
MyTown-1.6.1.11.jar
MyTownLib.jar
netherores-2.2.1-14.jar
opis_1.0.3b_alpha.zip
pam's harvestcraft 1.6.4 v1.1.4.zip
petbat_1.6.4.zip
powercrystalscore-1.1.8-9.jar
projectbench-1.6.2-v1.8.0.jar
random things v. 1.8.5 [MC 1.6.2].jar
ruins_1.6.4.zip
the lord of the rings mod Public Beta 11.zip
tradebooth.0.6.4.2.zip
tropicraft v5.1.6 mod for mc v1.6.4.jar
twilightforest-1.20.2.jar
weather v1.59 mod for mc v1.6.4.zip
zaw-1.1.033-beta-MC164.zip
zMineTweaker-1.6.4-2.2.4.zip
```

**Comment by shadowmage45** [comment]
Thanks for testing without MCPC present, that helps at least clear up one source of mods messing with things.

Also, thanks for the mod list, unfortunately, it does not help as much as it could -- I just don't have time to track down and download the mods (last time I tried doing that to find/solve an issue, it took several days of long hours of sorting out mod/id issues before I could even begin looking for the cause) (if you have a mod-pack d/l link though, I wouldn't mind going that route to find the issue).

What actions are you taking that produce the crash?  (e.g. opening footsoldier gui, attempting to place leather helmet in left-most armor slot(helmet)?)

(it could be something as simple as me forgetting some code in a particular NPCs gui, but would need more info to know where to start looking)

Thanks for helping me locate this issue, I'm sure we'll get it tracked down and fixed (or figure out what other mod needs fixing...either way).

**Comment by keenerb** [comment]
I'm planning on sorting through the mods and tracking it down, if it's a mod problem.  That just takes a little while.

**Comment by shadowmage45** [comment]
Thanks for that, I very much appreciate the effort you are putting in to help track this down.

Please let me know if you do locate a particular mod that is causing issues, I can likely help the author track down/fix their problem if needed, or possibly find/create a workaround in AW itself.

**Comment by keenerb** [comment]
It actually works fine in SSP.

Only in SMP does it crash.  I'll try just Ancient Warfare on SMP in a bit.

**Comment by keenerb** [comment]
Found it, I think.

One of these things is not like the other:

SMP:
http://i.imgur.com/bGBpZCP.png

SSP:
http://i.imgur.com/q0QxBpO.png

**Comment by shadowmage45** [comment]
Hmm..
Are both of those shots with only AW installed?

(for reference, the SSP screenshot has the correct positioning of the armor items)

**Comment by shadowmage45** [comment]
I just checked an dev/SMP setup (dedicated server, separate client...but both are run from source/dev code) (with only Ancient Warfare and BuildCraft installed), and still had no problems with interacting with the soldier inventory (still showed up in proper order as-per your SSP screenshot).

Very strange problem indeed.  Please let me know if you come across any further information regarding this, as now I'm quite curious as to the cause.

**Comment by keenerb** [comment]
Fresh minecraftforge 953 installation, no other mods except Ancient warfare on client OR server...

**Comment by shadowmage45** [comment]
Hmm...I will try updating my dev environment to see if that is the cause (building with Forge 871), though honestly Forge should not be changing that kind of stuff on their 'stable' branch for the current MC version (usually they save it for inbetween MC versions).

**Comment by keenerb** [comment]
Um, you can hold off on that.  I think I figured out what I'm doing wrong.  Give me a minute to verify.

**Comment by keenerb** [comment]
So, APPARANTLY, you actually have to upgrade the server AND the client when you update to a new version.

WHO KNEW?

Seriously though, that's pretty embarassing, and I bet this is why my mailbox top slot keeps resetting also.

**Comment by shadowmage45** [comment]
:)

Very well could be the root of the problem.  Please let me know if it resolves the issues with the mailbox as well.
